CREATE DATABASE IF NOT EXISTS associatecompanymanagement;

 CREATE TABLE `associatecompany` (
  `COMPANY_AIID` int NOT NULL AUTO_INCREMENT,
  `DELETECOMPANY` tinyint DEFAULT '0',
  `COMPANY_NAME_EN` varchar(45) DEFAULT NULL,
  `SHOW_COMPANYNAME_EN` tinyint DEFAULT '0',
  `COMPANY_NAME_JP` varchar(45) DEFAULT NULL,
  `SHOW_COMPANY_NAME_JP` tinyint DEFAULT '0',
  `COMPANY_NAME_CN` varchar(45) DEFAULT NULL,
  `SHOW_COMPANY_NAME_CN` tinyint DEFAULT '0',
  `ESTABLISHMENT_DATE_YEAR` varchar(45) DEFAULT NULL,
  `ESTABLISHMENT_DATE_MONTH` varchar(45) DEFAULT NULL,
  `ESTABLISHMENT_DATE_DATE` varchar(45) DEFAULT NULL,
  `CAPITAL` varchar(45) DEFAULT NULL,
  `WEBSITE` varchar(200) DEFAULT NULL,
  `Director` varchar(45) DEFAULT NULL,
  `JOB_DESCRIPTION` varchar(200) DEFAULT NULL,
  `INQUIRY_EMAIL` varchar(45) DEFAULT NULL,
  `CARRIER_EMAIL` varchar(45) DEFAULT NULL,
  `INVOICE_EMAIL` varchar(45) DEFAULT NULL,
  `REMARKS` varchar(45) DEFAULT NULL,
  `ASSOCIATECOMPANY_CREAT_TIME` varchar(45) DEFAULT NULL,
  `JOINDATE_YEAR` int DEFAULT NULL,
  `JOINDATE_MONTH` int DEFAULT NULL,
  PRIMARY KEY (`COMPANY_AIID`)
) 